#ifndef FILE_053_OBJNUM_077_48X30_6_19_26_H
#define FILE_053_OBJNUM_077_48X30_6_19_26_H

#include <stdint.h>

/* Auto-generated by BMP_parser.py
 * Image : File_053_ObjNum_077_48x30_6_19_26
 * Size  : 48 x 30 pixels
 * Layout: 6 byte(s)/row x 30 rows = 57 bytes total
 * Pixel 0,0 is top-left.
 */

static const uint8_t File_053_ObjNum_077_48x30_6_19_26_DATA[57U] = {
     0x78,  /* 120 	*/
     0x04,  /* 4 	*/
     0x2C,  /* 44 	*/
     0x04,  /* 4 	*/
     0x2C,  /* 44 	*/
     0x04,  /* 4 	*/
     0x2C,  /* 44 	*/
     0x06,  /* 6 	*/
     0x2A,  /* 42 	*/
     0x06,  /* 6 	*/
     0x2A,  /* 42 	*/
     0x08,  /* 8 	*/
     0x28,  /* 40 	*/
     0x08,  /* 8 	*/
     0x28,  /* 40 	*/
     0x08,  /* 8 	*/
     0x18,  /* 24 	*/
     0x1A,  /* 26 	*/
     0x16,  /* 22 	*/
     0x1A,  /* 26 	*/
     0x16,  /* 22 	*/
     0x1C,  /* 28 	*/
     0x14,  /* 20 	*/
     0x1C,  /* 28 	*/
     0x14,  /* 20 	*/
     0x1C,  /* 28 	*/
     0x14,  /* 20 	*/
     0x1E,  /* 30 	*/
     0x12,  /* 18 	*/
     0x1E,  /* 30 	*/
     0x12,  /* 18 	*/
     0x1C,  /* 28 	*/
     0x14,  /* 20 	*/
     0x1C,  /* 28 	*/
     0x14,  /* 20 	*/
     0x1C,  /* 28 	*/
     0x14,  /* 20 	*/
     0x1A,  /* 26 	*/
     0x16,  /* 22 	*/
     0x1A,  /* 26 	*/
     0x26,  /* 38 	*/
     0x08,  /* 8 	*/
     0x28,  /* 40 	*/
     0x08,  /* 8 	*/
     0x28,  /* 40 	*/
     0x08,  /* 8 	*/
     0x28,  /* 40 	*/
     0x06,  /* 6 	*/
     0x2A,  /* 42 	*/
     0x06,  /* 6 	*/
     0x2A,  /* 42 	*/
     0x04,  /* 4 	*/
     0x2C,  /* 44 	*/
     0x04,  /* 4 	*/
     0x2C,  /* 44 	*/
     0x04,  /* 4 	*/
     0x14,  /* 20 	*/
};

static const Image_t File_053_ObjNum_077_48x30_6_19_26 = {
     .width = 48,
     .height = 30,
     .size = 57,
     .data = File_053_ObjNum_077_48x30_6_19_26_DATA
};

#endif /* FILE_053_OBJNUM_077_48X30_6_19_26_H */
