#ifndef FILE_064_OBJNUM_099_48X63_6_19_26_H
#define FILE_064_OBJNUM_099_48X63_6_19_26_H

#include <stdint.h>

/* Auto-generated by BMP_parser.py
 * Image : File_064_ObjNum_099_48x63_6_19_26
 * Size  : 48 x 63 pixels
 * Layout: 6 byte(s)/row x 63 rows = 24 bytes total
 * Pixel 0,0 is top-left.
 */

static const uint8_t File_064_ObjNum_099_48x63_6_19_26_DATA[24U] = {
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xDB,  /* 219 	*/
};

static const Image_t File_064_ObjNum_099_48x63_6_19_26 = {
     .width = 48,
     .height = 63,
     .size = 24,
     .data = File_064_ObjNum_099_48x63_6_19_26_DATA
};

#endif /* FILE_064_OBJNUM_099_48X63_6_19_26_H */
