#ifndef FILE_063_OBJNUM_098_176X33_6_19_26_H
#define FILE_063_OBJNUM_098_176X33_6_19_26_H

#include <stdint.h>

/* Auto-generated by BMP_parser.py
 * Image : File_063_ObjNum_098_176x33_6_19_26
 * Size  : 176 x 33 pixels
 * Layout: 22 byte(s)/row x 33 rows = 55 bytes total
 * Pixel 0,0 is top-left.
 */

static const uint8_t File_063_ObjNum_098_176x33_6_19_26_DATA[55U] = {
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0x8F,  /* 143 	*/
     0xA2,  /* 162 	*/
     0x0E,  /* 14 	*/
     0xA2,  /* 162 	*/
     0x0E,  /* 14 	*/
     0xA2,  /* 162 	*/
     0x0E,  /* 14 	*/
     0xA2,  /* 162 	*/
     0x0E,  /* 14 	*/
     0xA2,  /* 162 	*/
     0x0E,  /* 14 	*/
     0xA2,  /* 162 	*/
     0x0E,  /* 14 	*/
     0xA2,  /* 162 	*/
     0x0E,  /* 14 	*/
     0xA2,  /* 162 	*/
     0x0E,  /* 14 	*/
     0xA2,  /* 162 	*/
     0x0E,  /* 14 	*/
     0xA2,  /* 162 	*/
     0x0E,  /* 14 	*/
     0xA2,  /* 162 	*/
     0x0E,  /* 14 	*/
     0xA2,  /* 162 	*/
     0x0E,  /* 14 	*/
     0xA2,  /* 162 	*/
     0x0E,  /* 14 	*/
     0xA2,  /* 162 	*/
     0x0E,  /* 14 	*/
     0xA2,  /* 162 	*/
     0x0E,  /* 14 	*/
     0xA2,  /* 162 	*/
     0x0E,  /* 14 	*/
     0xA2,  /* 162 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0x89,  /* 137 	*/
};

static const Image_t File_063_ObjNum_098_176x33_6_19_26 = {
     .width = 176,
     .height = 33,
     .size = 55,
     .data = File_063_ObjNum_098_176x33_6_19_26_DATA
};

#endif /* FILE_063_OBJNUM_098_176X33_6_19_26_H */
