#ifndef FILE_065_OBJNUM_104_16X30_6_19_26_H
#define FILE_065_OBJNUM_104_16X30_6_19_26_H

#include <stdint.h>

/* Auto-generated by BMP_parser.py
 * Image : File_065_ObjNum_104_16x30_6_19_26
 * Size  : 16 x 30 pixels
 * Layout: 2 byte(s)/row x 30 rows = 42 bytes total
 * Pixel 0,0 is top-left.
 */

static const uint8_t File_065_ObjNum_104_16x30_6_19_26_DATA[42U] = {
     0x00,  /* 0 	*/
     0x54,  /* 84 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x08,  /* 8 	*/
     0x54,  /* 84 	*/
};

static const Image_t File_065_ObjNum_104_16x30_6_19_26 = {
     .width = 16,
     .height = 30,
     .size = 42,
     .data = File_065_ObjNum_104_16x30_6_19_26_DATA
};

#endif /* FILE_065_OBJNUM_104_16X30_6_19_26_H */
